apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ralonso-roleBindig
  namespace: ns-ralonso
roleRef:
  kind: Role
  name: ns-ralonso-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
  name: ralonso@stemdo.io
  namespace: ralonso
