apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: palonso-roleBindig
  namespace: ns-palonso
roleRef:
  kind: Role
  name: ns-palonso-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
  name: palonso@stemdo.io
  namespace: palonso
