apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dnazareno-roleBindig
  namespace: ns-dnazareno
roleRef:
  kind: Role
  name: ns-dnazareno-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
  name: dnazareno@stemdo.io
  namespace: dnazareno
