apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: plopez-roleBindig
  namespace: ns-plopez
roleRef:
  kind: Role
  name: ns-plopez-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
  name: plopez@stemdo.io
  namespace: plopez
