apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jbeltran-roleBindig
  namespace: ns-jbeltran
roleRef:
  kind: Role
  name: ns-jbeltran-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
  name: jbeltran@stemdo.io
  namespace: jbeltran
