apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jbeltran-clusterRoleBindig
roleRef:
  kind: ClusterRole
  name: storageclass-reader
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
  name: jbeltran@stemdo.io
  namespace: jbeltran

