apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: icasado-roleBindig
  namespace: ns-icasado
roleRef:
  kind: Role
  name: ns-icasado-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
  name: icasado@stemdo.io
  namespace: icasado
