apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: storageclass-reader
rules:
- apiGroups: ["", "storage.k8s.io"]
  resources: ["storageclasses", "persistentvolumes"]
  verbs: ["get", "watch", "list"]