apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eperez-roleBindig
  namespace: ns-eperez
roleRef:
  kind: Role
  name: ns-eperez-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
  name: eperez@stemdo.io
  namespace: eperez
