apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lcabrita-roleBindig
  namespace: ns-lcabrita
roleRef:
  kind: Role
  name: ns-lcabrita-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
  name: lcabrita@stemdo.io
  namespace: lcabrita
