name: Deploy to AKS

on:
  workflow_dispatch:

jobs:
  deploy-k8s:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Get AKS credentials
      run: az aks get-credentials --resource-group final-project-common --name aksbootcampwe01 

    - name: Get AKS credentials
      run: az aks install-cli

    - name: Deploy to AKS
      run: |
        kubectl apply -f k8s/jbeltran


