name: Deploy to AKS

on:
  workflow_run:
    workflows: ["Terraform Apply"]
    types:
      - completed

jobs:
  deploy-k8s:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up kubelogin for non-interactive login
      uses: azure/use-kubelogin@v1
      with:
         kubelogin-version: 'v0.0.24'

    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: azure/aks-set-context@v3
      with:
        resource-group: 'final-project-common'
        cluster-name: 'aksbootcampwe01'
        admin: 'false'
        use-kubelogin: 'true'

    - name: Deploy to AKS
      run: |
            for dir in k8s/*; do
              if [ -d "$dir" ]; then
                for file in "$dir"/*.yaml; do
                  kubectl apply -f "$file"
                done
              fi
            done




